
<h1 align=center> Linear Algebra: Chapter 10 (Orthognality And Transformation)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

Orthognality: Two lines, segments, or planes are said to be orthogonal if they’re perpendicular to one another. The slope of a line is determined by finding the difference between the y-coordinates of two points on the line and dividing that difference by the difference between the corresponding x-coordinates of the points on that line.

And, further, two lines are perpendicular (form a right angle) if the product of their slopes is –1. (Then they’re negative reciprocals of one another.). Note:(The reciprocal of a number is equal to 1 divided by the number.)

When dealing with vectors, you determine if they’re perpendicular to one another by finding their inner product. If the inner product of vectors uTv(the transpose of u multiplied by v) is equal to 0, then the vectors are perpendicular. This means the angle between them is 90 degrees.

## Checking perpendicularity using slopes

Checking perpendicularity using the transpose of one vector

In [ ]:
import numpy as np
u2=np.array([6,2])
v2=np.array([-1,3])

print(u2.dot(v2.transpose())) # the inner product/ The dot product equals 0. this means the angle between the vectors is 90 degrees
print(v2.dot(u2.transpose()))

0
0


Measuring the angle between 2 vectors u and v: 

 u.v=||u||.||v||cosθ

where u · v is the inner product of the two vectors, ||u|| and ||v|| are the respective magnitudes of the vectors, and cosθ is the measure (counterclockwise) of the angle formed between the two vectors.

In [ ]:
u3=np.array([6,2])
v3=np.array([-1,3])
innerAngleCosine=(u3.dot(v3))/(np.linalg.norm(u3)*np.linalg.norm(v3))
print(innerAngleCosine)

0.0


It is always good in data science to use orthognal matrices when we transform our data as it will ease claculating the transpose and the inverse which will ease the transformation

A n×n matrix A is an orthogonal matrix if its transpose is equal to its inverse & if we multiply the matrix by its transpose, The result is the identity matrix. also the determinant of the matrix is =+/-1. rows are orthognal to each other and also columns.

We normally use The Gram-Scmidt process to form orthognal basis vector set to make orthognal transformation.

An orthogonal set is a set of vectors in which each pair of vectors is orthogonal(every vector is orthogonal to every other vector in the set).

An orthogonal set is linearly independent, as long as the set doesn’t contain the 0 vector.

## Checking orthognality by the transpose of a matrix

In [ ]:
myMatrix=np.array([[1,2],[3,4]])
myMatrixTransposed=myMatrix.transpose()
myMatrixTransposed

array([[1, 3],
       [2, 4]])

In [ ]:
myMatrixInversed=np.linalg.inv(myMatrix)
myMatrixInversed # it is clear that the transpose doesn't equal the inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
myMatrix=np.array([[-0.3092,-0.9510],[-0.9510, 0.3092]])
myMatrixTransposed=myMatrix.transpose()
myMatrixTransposed

array([[-0.3092, -0.951 ],
       [-0.951 ,  0.3092]])

## Checking orthognality by the inverse of a matrix

In [ ]:
myMatrixInversed=np.linalg.inv(myMatrix)
myMatrixInversed # it is clear that the transpose equals the inverse

array([[-0.30919826, -0.95099464],
       [-0.95099464,  0.30919826]])

In [ ]:
myMatrixTransposed*myMatrix

array([[0.09560464, 0.904401  ],
       [0.904401  , 0.09560464]])

In [ ]:
myMatrix*myMatrixTransposed

array([[0.09560464, 0.904401  ],
       [0.904401  , 0.09560464]])

## Determinant of orthognal matrix

In [ ]:
np.linalg.det(myMatrix) #the determinant equals -1==> orthognal matrix

-1.00000564

In [ ]:
# using the Gram-Schmidt process to form an orthognal matrix from a non-orthoganl matrix
def gram_schmidt_columns(X):
    Q, R = np.linalg.qr(X)
    return Q
nonOrthoMatrix=np.array([[1,-1,0],[-2,3,1],[1,2,4]])
print(gram_schmidt_columns(np.asarray(nonOrthoMatrix)))

[[-0.40824829  0.0531494  -0.91132238]
 [ 0.81649658 -0.4251952  -0.39056673]
 [-0.40824829 -0.90353981  0.13018891]]


In [ ]:
np.linalg.det(gram_schmidt_columns(np.asarray(nonOrthoMatrix))) # the determinant equals 1==> orthognal matrix

1.0000000000000004

The orthonormal basis:

An orthonormal basis consists of vectors that all have a magnitude. The magnitude of a vector, designated ||v|| is the square root of the sum of the squares of the elements of the vector.

The process needed to change to an orthonormal basis is really relatively simple. You just multiply each vector in the orthogonal basis by the reciprocal of the square root of its inner product.

Note: (The reciprocal of a number is equal to 1 divided by the number.)

In [ ]:
import scipy.linalg as sc
print(sc.orth(gram_schmidt_columns(np.asarray(nonOrthoMatrix))))
print(sc.orth(gram_schmidt_columns(np.asarray(nonOrthoMatrix)))[:,0])# the first column
print(np.linalg.norm(sc.orth(gram_schmidt_columns(np.asarray(nonOrthoMatrix)))[:,0]))# the norm/ magnitude of it is 1
print(np.linalg.norm(sc.orth(gram_schmidt_columns(np.asarray(nonOrthoMatrix)))[:,1]))# the norm/ magnitude of it is 1
print(np.linalg.norm(sc.orth(gram_schmidt_columns(np.asarray(nonOrthoMatrix)))[:,2]))# the norm/ magnitude of it is 1
# s all the magnitudes equal 1 ===> the matrix is orthonormal

[[-0.79134238 -0.40824829 -0.45509403]
 [-0.53948658  0.81649658  0.2056394 ]
 [-0.28763078 -0.40824829  0.86637282]]
[-0.79134238 -0.53948658 -0.28763078]
1.0
1.0
1.0
