
<h1 align=center> Linear Algebra: Chapter 2 (Matrices)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

# Introduction to matrices

Matrices are essentially rectangular arrays of numbers. The reason
that you’d ever even consider putting numbers in rectangular arrays
is to give some order or arrangement to them so that they can be studied or used in an application.

The rectangular arrays of numbers are surrounded by a bracket to
indicate that this is a mathematical structure called a matrix. The different
positions or values in a matrix are called elements
A is a 3 × 4 matrix where aij = i + j.

Matrices come in all sizes or dimensions. The dimension gives the number of
rows, followed by a multiplication sign, followed by the number of columns.

Determining the dimension of a matrix is important when performing operations involving more than one matrix. When adding or 
subtracting matrices, the two matrices need to have the same dimension. When multiplying matrices, the number of columns in the 
first matrix has to match the number of columns in the second matrix.

# sales scenario

Here we  build 2 matrices; one represents the sales of 3 insurance-policies sales representatives in January and the other represents the sales of the same 2 in February. The policies sold are represented by the columns; Life insurence, car insuarence, and homeowner insurance

The rectangular array allows the sales manager to quickly observe any trends or patterns or problems with the production of the salespersons.

In [1]:
import numpy as np
matrixJan=np.array([[12,23,14],[20,29,38],[3,6,10]])
matrixFeb=np.array([[13,33,22],[10,19,8],[30,0,20]])
sumJanFeb=matrixJan+matrixFeb
print(sumJanFeb)

sumFebJan=matrixFeb+matrixJan
print(sumFebJan)# matrix addition is cummutative

[[25 56 36]
 [30 48 46]
 [33  6 30]]
[[25 56 36]
 [30 48 46]
 [33  6 30]]


## matrix scalar multiplication

In [3]:
print(-4*sumJanFeb)

[[-100 -224 -144]
 [-120 -192 -184]
 [-132  -24 -120]]


## matrix multiplication

In [16]:
# to multiply matrices, columns of the first should equal rows of the second
matrixA=np.array([[1,1],[2,2],[3,3],[4,4]]) # a matrix of 4*2
matrixB=np.array([[1,1,1,1],[2,2,2,2,],[3,3,3,3],[4,4,4,4],[5,5,5,5]]) # a matrix of 5*4
print(np.matmul(matrixB,matrixA))

[[10 10]
 [20 20]
 [30 30]
 [40 40]
 [50 50]]


## the identity matrix

identity matrix (the matrix that makes no change for the vector or the matrix) transformation - no change in the vector or the matrix. 
There are 2 identity matrices; the additive identity and the multiplicative identity.

The additive identity for matrices is the zero matrix. A zero matrix has elements that are all zero.

The multiplicative identity comes in only one shape: a square. A square matrix is n × n; the number of rows and number of columns is the same.
The multiplicative identity is a square matrix, and the elements on the maindiagonal running from the top left to the bottom 
right are 1s. All the rest of the elements in the matrix are 0s.

In [7]:
identityAdd=np.array([[0,0],[0,0],[0,0],[0,0]])
print(matrixA)
print('#########')
print(matrixA+identityAdd)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
#########
[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [8]:
identityMul=np.array([[1,0],[0,1]])
print(matrixA)
print('#########')
print(np.matmul(matrixA,identityMul))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
#########
[[1 1]
 [2 2]
 [3 3]
 [4 4]]


**matrix multiplication, in general, is not commutative**. The **exception** to that rule is when a square matrix is multiplied by its identity matrix. Whether the identity matrix comes first or second in the multiplication, the original matrix keeps its identity

In [10]:
squarematrixA=np.array([[4,-1],[2,3]])
identityMul=np.array([[1,0],[0,1]])
print(np.matmul(squarematrixA,identityMul))#multiplication is only commutative in this case
print('#########')
print(np.matmul(identityMul,squarematrixA))#multiplication is only commutative in this case

[[ 4 -1]
 [ 2  3]]
#########
[[ 4 -1]
 [ 2  3]]


<h3>NOTE:</h3>

**Matrices labeled as being triangular or diagonal** have the common characteristic that they’re square matrices. A triangular  matrix is either upper triangular or lower triangular.An upper triangular matrix; all the elements below the main diagonal (the diagonal running from upper left to lower right) are 0s.A lower triangular matrix; all the elements above the main diagonal are 0s.

# singular and non-singular matrices

The classification as singular or non-singular matrices applies to just square matrices. A square matrix is singular if it has a multiplicative inverse; a matrix is non-singular if it does not have a multiplicative inverse.

singular=لها معكوس ضربي
non-singular= ليس لها معكوس ضربي


When a matrix has a multiplicative inverse, the product of the matrix and its inverse is equal to an identity matrix (multiplicative identity). And, furthermore, you can multiply the two matrices involved in either order (commutativity) and still get the identity.

An invertible matrix is a matrix that has an inverse. An invertible matrix is a square matrix. If matrix A is invertible, then there’s also a matrix A–1 where, when you multiply the two matrices, A * A–1, you get an identity matrix of the same dimension as A and A–1. When you multiply a matrix and its inverse together, the order doesn’t matter. Either order of multiplication produces the identity matrix.

Not all matrices are invertible. For example, a matrix with a row of 0s or a column of 0s isn’t invertible — it has no inverse.

Matrix inverses are used to solve problems involving systems of equations and to perform matrix division.

In [13]:
orginalMatrix=np.array([[4,-7],[2,-3]])
inverseMatrix=np.linalg.inv(orginalMatrix)
print('the inverse of the original matrix is: '+str(inverseMatrix))

print('################')
print('the product of the matrix and its inverse in this order (matrix*inverse) is: '+str(np.matmul(orginalMatrix,inverseMatrix)))
print('################')
print('the product of the matrix and its inverse in this order (inverse*matrix) is: '+str(np.matmul(inverseMatrix,orginalMatrix)))
#notice that whatever the order, the result is the identity matrix


the inverse of the original matrix is: [[-1.5  3.5]
 [-1.   2. ]]
################
the product of the matrix and its inverse in this order (matrix*inverse) is: [[1. 0.]
 [0. 1.]]
################
the product of the matrix and its inverse in this order (inverse*matrix) is: [[1. 0.]
 [0. 1.]]


In [14]:
# there are matrices without inverse

In [17]:
matrixWithNoInverse=np.array([[8,2],[12,3]])
print(np.linalg.inv(matrixWithNoInverse)) # the result shows that it is a singular matrix

LinAlgError: ignored

#Matrix transpose

Performing a matrix transpose on matrix A, the notation is AT. When A is changed to AT, each aij in A becomes aij in AT:

In [19]:
originalMatrix=np.array([[6,7,8],[-1,3,5]])
print(originalMatrix)
print('###################')
transposedMatrix=originalMatrix.transpose()
print(transposedMatrix)

[[ 6  7  8]
 [-1  3  5]]
###################
[[ 6 -1]
 [ 7  3]
 [ 8  5]]


The transpose of the sum of two matrices is equal to the sum of the two transposes:

In [20]:
print(originalMatrix)
print('###################')
print(originalMatrix.transpose())
print('###################')

anotherMatrix=np.array([[5,9,14],[5,4,7]])
print(anotherMatrix.transpose())
print('###################')
sumOfTransposes=anotherMatrix.transpose()+originalMatrix.transpose()
print('Sum of transposes is:'+str(sumOfTransposes))
print('###################')

sumOriginalAdded=originalMatrix+anotherMatrix
print(sumOriginalAdded)
print('###################')
transposeOfSum=sumOriginalAdded.transpose()
print('Transpose of sums is: '+str(transposeOfSum))


[[ 6  7  8]
 [-1  3  5]]
###################
[[ 6 -1]
 [ 7  3]
 [ 8  5]]
###################
[[ 5  5]
 [ 9  4]
 [14  7]]
###################
Sum of transposes is:[[11  4]
 [16  7]
 [22 12]]
###################
[[11 16 22]
 [ 4  7 12]]
###################
Transpose of sums is: [[11  4]
 [16  7]
 [22 12]]


The transpose of the product of two matrices is equal to the product of the two transposes in the opposite order:

In [21]:
matrixA=np.array([[1,1],[2,2],[3,3],[4,4]])
matrixB=np.array([[1,1,1,1],[2,2,2,2,],[3,3,3,3],[4,4,4,4],[5,5,5,5]])
productOfMatrices=np.matmul(matrixB,matrixA)
print('Product of the matrices: '+str(productOfMatrices))
print('###################')
print('transpose of the product of the 2 matrices is: '+str(productOfMatrices.transpose()))
print('###################')
productOfTransposes=np.matmul(matrixA.transpose(),matrixB.transpose())#this is the product of transposes but in the opposite order
print('product of transposes is: '+str(productOfTransposes))

Product of the matrices: [[10 10]
 [20 20]
 [30 30]
 [40 40]
 [50 50]]
###################
transpose of the product of the 2 matrices is: [[10 20 30 40 50]
 [10 20 30 40 50]]
###################
product of transposes is: [[10 20 30 40 50]
 [10 20 30 40 50]]
