
<h1 align=center> Linear Algebra: Chapter 3 (Systems of equations)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

# Introduction to systems of equations

A system of equations has a solution when you have at least one set of numbers that replaces the variables in the equations and makes each equation read as a true statement. A system of equations may have more than one solution.

A system of equations is consistent if it has at least one solution. A system with exactly one solution has two characteristics that distinguish it from other systems: The system consists of linear equations, and you have as many independent equations as there are variables (If the system contains three variables, then it must contain at least three independent equations.)

In [1]:
# 2 equations with one solution
# 1a + 1b = 35
# 2a + 4b = 94

import numpy as np
leftSide = np.array([[1, 1],[2,4]])
rightSide = np.array([35, 94])

print(np.linalg.solve(leftSide,rightSide))
print('#########')
print(np.linalg.lstsq(leftSide,rightSide, rcond=None)[0])#to get infinite solutions, we use lstsq

[23. 12.]
#########
[23. 12.]


In [2]:
leftSide = np.array([[2,3],[4,-3]])
rightSide = np.array([23,1])
print(np.linalg.solve(leftSide,rightSide))

[4. 5.]


In [3]:
#3 equations with one solution
# 2x+3y+z=14
# 4x-y+5z=10
# x+2y-3z=5

leftSide=np.array([[2,3,1],[4,-1,5],[1,2,-3]])
rightSide=np.array([14,10,5])
print(np.linalg.solve(leftSide,rightSide))#to get one solution, we use solve
print('#########')
print(np.linalg.lstsq(leftSide,rightSide, rcond=None)[0])#to get infinite solutions, we use lstsq
## the values that makes the system of equations consistent are  x=2, y=3, z=0

[2. 3. 1.]
#########
[2. 3. 1.]


In [4]:
# 3 equations with infinite number of solutions
# -x+y+z=-1
# -x+2y-3z=-4
# 3x-2y-7z=0

leftSide=np.array([[-1,1,1],[-1,2,-3],[3,-2,-7]])
rightSide=np.array([-1,-4,0])
print(np.linalg.solve(leftSide,rightSide))# the values that makes the system of equations consistent are  x=-2, y=-3, z=0
print('#########')
print(np.linalg.lstsq(leftSide,rightSide, rcond=None)[0])

[-2. -3.  0.]
#########
[ 0.61904762 -0.9047619   0.52380952]


In [5]:
# 2 equations with no solution
# 2x +  y = 5
# 6x + 3y = 1

leftSide = np.array([[2, 1],[6,3]])
rightSide = np.array([5, 1])

print(np.linalg.lstsq(leftSide,rightSide, rcond=None))
print(np.linalg.solve(leftSide,rightSide))# it gives singular matrix and this means there is no solution. may be the lines are parallel

(array([0.32, 0.16]), array([], dtype=float64), 1, array([7.07106781e+00, 4.77629022e-16]))


LinAlgError: ignored

In [6]:
# augmented matrix
leftSide=np.array([[-1,-1,-1],[4,5,0],[0,1,-3]])
rightSide=np.array([3,-6,5])
print(np.linalg.solve(leftSide,rightSide))

[-4.  2. -1.]


In [7]:
leftSide = np.array([[.10,.50,.15],[.05,0,.15],[0,.4,.1]])
rightSide = np.array([1,1,1])
print(np.linalg.solve(leftSide,rightSide))

[-4.54545455  0.45454545  8.18181818]


In [8]:
# check the solution
np.matmul(leftSide, np.linalg.solve(leftSide,rightSide))

array([1., 1., 1.])

In [9]:
leftSide = np.array([[-1,-1,-1],[4,5,0],[0,1,-3]])
rightSide = np.array([3,-6,5])
print(np.linalg.solve(leftSide,rightSide))

[-4.  2. -1.]


# solving non-linear equations using numpy

In [10]:
# eample source: https://www.youtube.com/watch?v=S4Qg2CsiIj8

from numpy import*
from scipy.optimize import *


def func(z):
    x = z[0]
    y = z[1]
    #L = X[2] # this is the multiplier. lambda is a reserved keyword in python
    
    F=empty((2))# create a list of 2 dimensions but empty
    F[0]=pow(x,2)+pow(y,2)-20 # x**2+y**2-20
    F[1]=y-pow(x,2)
    
    return F

# let us create some guess values of z by creating an array and making the guess values of x,y as 1,1
zGuess=array([1,1])
z=fsolve(func,zGuess)
print(z)

[2. 4.]
