
<h1 align=center> Linear Algebra: Chapter 4 (Multiply matrix by vector)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

# introduction

Matrices have two completely different types of products (matrix by vector & matrix by matrix). When preparing to perform multiplication involving matrices, you first take note of why you want to multiply them and then decide how. When you multiply an m × n matrix times an n × p matrix, your result is an m × p matrix. To multiply a matrix by a vector in Python, we can use "matmul" or "dot".

In [1]:
import numpy as np
myVector=np.array([1,-3,2,2]) #original vector
myMatrix=np.array([[2,3,1,0],[-1,4,1,-3]])
matrixByVector=myMatrix.dot(myVector)
print (matrixByVector)
print('##########')
print(np.matmul(myMatrix,myVector))

[ -5 -17]
##########
[ -5 -17]


Finding x in the equation Ax=b.... we conside matrix A multiplied by x (the unknown) as the leftSide and vector b as the right side and we solve it (either it has one of infinite or no solution)

In [3]:
b=np.array([2,10,20,17])
A=np.array([[1,-2,2,1],[1,-1,5,0],[2,-2,11,2],[0,2,8,1]])
x=np.linalg.solve(A,b)
print(x)
print('#######################')
print(np.linalg.lstsq(A,b, rcond=None))
print('#######################')
print(A.dot(x)) # now we are sure that Ax=b=[2,10,20,17]

[ 1.  1.  2. -1.]
#######################
(array([ 1.,  1.,  2., -1.]), array([], dtype=float64), 4, array([14.96840391,  3.74321874,  0.96688002,  0.01845894]))
#######################
[ 2. 10. 20. 17.]


In [4]:
b=np.array([-30,90,45])
A=np.array([[-1,4,2],[3,0,-2],[5,4,3]])
x=np.linalg.solve(A,b)
print(x)

[ 16.   7. -21.]
