
<h1 align=center> Linear Algebra: Chapter 5 (Homogenous systems & linear independence)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

# homogenous systems

Homogeneous systems of equations are set equal to 0, and then you try to find nonzero solutions — an interesting challenge. Homogenous systems of eqution has the below form

ax+by+cz=0 & dx+ey+hz=0 & and so on

Homogenous system of equations has two types of solutions; trivial solution & non-trivial solution. Unlike a general system of linear equations, a homogeneous system of linear equations always has at least one solution — a solution is guaranteed. The guaranteed solution occurs when you let each variable be equal to 0. The solution where everything is 0 is called the trivial solution.

A homogeneous system of linear equations has a nontrivial solution if and only if the system has at least one free variable. A free variable (also called a parameter) is a variable that can be randomly assigned some numerical value. 

 يمكن أن تعطيه أي قيمة رقمية

The other variables are then related to the free variable through some algebraic rules.

In [2]:
# a system with a trivial solution  (a guranteed solution that occurs when you let each variable be equal to 0) and no 
# nontrivial solutions

# 3x+4y=0
# 4x-2y=0

import numpy as np
leftSide=np.array([[3,4],[4,-2]])
rightSide=np.array([0,0])

print(np.linalg.solve(leftSide,rightSide))
print('#########')
print(np.linalg.lstsq(leftSide,rightSide, rcond=None))[0]

[0. 0.]
#########
(array([0., 0.]), array([], dtype=float64), 2, array([5.21699057, 4.21699057]))


TypeError: ignored

In [3]:
# a system with a nontrivial solution but we cannot get it using numpy
# x+3y-5z=0
# 3x-y+5z=0
# 3x+2y-z=0

leftSide=np.array([[1,3,-5],[3,-1,5],[3,2,-1]])
rightSide=np.array([0,0,0])

print(np.linalg.solve(leftSide,rightSide))
print('#########')
print(np.linalg.lstsq(leftSide,rightSide, rcond=None)[0])

[ 0.  0. -0.]
#########
[0. 0. 0.]
