
<h1 align=center> Linear Algebra: Chapter 6 (Linear Transformations)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

# introduction to transformations

Some transformations found in geometry are performed by moving objects around systematically and not changing their shape or size. Other transformations make more dramatic changes to geometric figures. Linear transformations even incorporate some of the geometric transformational processes. But linear transformations in this chapter have some restrictions, as well as opening up many more mathematical possibilities.

Linear transformations are very specific types of processes in mathematics. They often involve mathematical structures such as vectors and matrices; the transformations also incorporate mathematical operations. Some of the operations used by linear transformations are your everyday addition and multiplication; others are specific to the type of mathematical structure that the operation is being performed upon.

In mathematics, a transformation is an operation, function, or mapping in which one set of elements is transformed into another set of elementsز

A linear transformation is a particular type of transformation in which one set of vectors is transformed into another vector set using some linear operator. Also part of the definition of a linear transformation is that the sets and operator are bound by the following two properties:

1- Performing the transformation on the sum of any two vectors in the set has the same result as performing the transformation on the vectors independently and then adding the resulting vectors together.

2- Performing the transformation on a scalar multiple of a vector has the same result as performing the transformation on the vector and then multiplying by that scalar.

“Transformation T takes a 3 × 1 vector and transforms it into a 2 × 1 vector. The elements in the 2 × 1 vector are a sum and difference of some elements in the 3 × 1 vector.” Perform transformation (T) on a vector v by writing T(v) and we normally use the matrix A for transformation.

In [1]:
import numpy as np
v=np.array([5,1,-2])
A=np.array([[2,0,1],[3,1,-1],[4,3,0]])
Av=A.dot(v)
print(Av)
print('###################')
print(np.matmul(A,v))

[ 8 18 23]
###################
[ 8 18 23]


In [2]:
v=np.array([5,1,-2])
B=np.array([[2,3,0],[-1,-2,3]])
Bv=B.dot(v)
print(Bv)
print('###################')
print(np.matmul(B,v))

[ 13 -13]
###################
[ 13 -13]


In [3]:
# If T is a linear transformation matrix and u and v are vectors and c is a scalar, then:
# ✓ T(u + v) = T(u) + T(v)
# ✓ T(cv) = cT(v)

In [5]:
u=np.array([6,-5])
v=np.array([-4,-1])
T=np.array([[2,3],[-1,-2]])
print(u+v)
print('##################')
print(T.dot(u+v))
print('##################')
print(T.dot(u)+T.dot(v)) # same result as T(u+v)

[ 2 -6]
##################
[-14  10]
##################
[-14  10]


In [6]:
c=5
print(T.dot(c*v))
print('##################')
print(c*T.dot(v))# same result as T(c*v)

[-55  30]
##################
[-55  30]


# properties of transformations

Transformation composition is actually more like an embedded operation. When you perform the composition transformation T1 followed by transformation T2, you first perform transformation T2 on the vector v and then perform transformation T1 on the result.

Transformation composition is defined as (T1T2)(v)= T1(T2(v))

The associative property has to do with the grouping of the transformations,not the order. In general, you can’t change the order of performing transformations
and get the same result. But, with careful arrangements of transfor mations and dimension, you do get to see the associative property in action when composing transformations. The associative property states that when you perform transformation composition on the first of two transformations and then the result on a third, you get the same result as performing the composition on the last two transformations and then performing the transformation described by the first on the result of those second two.

Whew! It’s more understandable written symbolically: Given the vector v and the linear transformations T1, T2, and T3

([T1T2]T3)(v)= (T1[T2T3])(v)

In case of scalar multiplication, Given the vector v and the linear transformations T1 and T2:

c([T1T2])(v) = ([cT1]T2)(v) = (T1[cT2])(v)      or,

c[T1T2] = [cT1]T2 = T1[cT2]
No matter where you introduce the scalar multiple, the result is the same.

In [7]:
# (T1T2)(v)= T1(T2(v))
v=np.array([-4,-1])
T1=np.array([[1,0],[0,2]])
T2=np.array([[1,1],[0,1]])
print(T1.dot(T2).dot(v))
print('#############')
print(T1.dot(T2.dot(v)))# same result of (T1T2)(v)
print('#############')
print('#############')
print('#############')


print(T2.dot(T1).dot(v))# not the same result if we change the order of matrices
print('#############')
print(T2.dot(T1.dot(v)))

[-5 -2]
#############
[-5 -2]
#############
#############
#############
[-6 -2]
#############
[-6 -2]


In [8]:
originalVector=np.array([3,2]) #original vector

In [9]:
#stretching by 3 in X and 2 in Y
stretchingMatrix=np.array([[3,0],[0,2]])
stretchingMatrix.dot(originalVector)

array([9, 4])

## mirroring

In [10]:
# miroring over the line y=x
inversionMatrix=np.array([[0,1],[1,0]])
inversionMatrix.dot(originalVector)

array([2, 3])

In [11]:
# miroring over the line y=-x
inversionMatrix=np.array([[0,-1],[-1,0]])
inversionMatrix.dot(originalVector)

array([-2, -3])

In [12]:
# miroring over the y-axis
inversionMatrix=np.array([[-1,0],[0,1]])
inversionMatrix.dot(originalVector)

array([-3,  2])

In [13]:
# miroring over the x-axis
inversionMatrix=np.array([[1,0],[0,-1]])
inversionMatrix.dot(originalVector)

array([ 3, -2])

## shearing

In [14]:
inversionMatrix=np.array([[1,1],[0,1]])
inversionMatrix.dot(originalVector)

array([5, 2])

## rotation

In [15]:
inversionMatrix=np.array([[0,-1],[1,0]])
inversionMatrix.dot(originalVector)

array([-2,  3])

## null space

A special result of a linear transformation is that in which every element in the resulting vector is a 0. The kernel of a linear transformation is also referred to as the null space. The kernel and range of a linear transformation are related in that they’re both results of performing the linear transformation. The kernel is a special portion, and the range is everything that happens.

When the linear transformation T from a given set of vectors to another set of vectors results in one or more 0 vectors, then the original vectors, v1, v2, v3, . . .for which T(v) = 0 are called the kernel or null space of the set of vectors.

Nullspace: the nullspace of a matrix A is the set of vectors, that gives the zero vector, when multiplied by matrix A (e.g. Ax=0)

In [16]:
from sympy import Matrix
A = Matrix([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])
print(A.nullspace())

[Matrix([
[-15],
[  6],
[  1],
[  0],
[  0]]), Matrix([
[0],
[0],
[0],
[1],
[0]]), Matrix([
[   1],
[-1/2],
[   0],
[   0],
[   1]])]


In [17]:
A*A.nullspace()[0] # to be sure we multiply the nullspace by the first vector in the resulting matrix (nullspace matrix)

Matrix([
[0],
[0]])

In [18]:
A*A.nullspace()[1] # to be sure we multiply the nullspace by the second vector in the resulting matrix (nullspace matrix)

Matrix([
[0],
[0]])

Nullspace and the relation with linear independence: 

If the column vectors of the square matrix (columns after making them vectors) are linearly independent, the nullspace of the matrix is only going to be the zero vector. In other words, if the nullspace of the matrix is the zero vector, the column vectors (the columns) of the matrix are linearly independent

In [20]:
B=Matrix([[2,5,3],[1,1,1],[4,-2,0]])
# myLinearlyIndependentColumns= Matrix([[2,1,4],[5,1,-2],[3,1,0]])
B.nullspace() # the result is the zero vector. In the next cell, let us check if the column vectors are linearly independent

[]

In [21]:
B=np.array([[2,5,3],[1,1,1],[4,-2,0]])
print(B)
print(np.linalg.det(B)) # the determinant is not zero. So, the matrix is linearly independent

# here, we transpose the matrix
V =  np.transpose(B)#transpose
print(V)
np.linalg.det(V) # the determinant is not zero. So, the transpose of the matrix is linearly independent

[[ 2  5  3]
 [ 1  1  1]
 [ 4 -2  0]]
5.999999999999998
[[ 2  1  4]
 [ 5  1 -2]
 [ 3  1  0]]


5.999999999999996