
<h1 align=center> Linear Algebra: Chapter 7 (Determinants)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

# introduction to determinants

Determinants are linked with square matrices. You compute determinants of matrices using the elements in the matrices. Determinants are linked with square matrices. You compute determinants of matrices using the elements in the matrices. Determinants are used in many applications that you find in this part.

A determinant is a number associated with a square matrix; the determinant is a single number of worth. The number you get for a determinant is created using products of elements in the matrix along with sums and differences of those products.

The detrminant is a property of the square matrix. It calculates the area of the matrix (in case of 2D and the size in case of 3D). It is also the amount that the matrix stretches the space by. When we divide by the determinant , after transformation, we reach/ normalize the space back to its original size.

In [1]:
#calculating the determinant for a 2x2 matrix
import numpy as np
my2Matrix=np.array([[3,4],[1,2]])
np.linalg.det(my2Matrix)

2.0000000000000004

In [2]:
#calculating the determinant for a 3x3 matrix with a non-zero determinant (we can solve the equation system/ the matrix & it has an inverse)
my3Matrix=np.array([[3,0,-1],[2,4,1],[7,2,3]])
np.linalg.det(my3Matrix)

53.999999999999986

**Note about linearly independent vectors** ==> A set of vectors are linearly dependent, that is if one of the vectors is some combination of the others.Vectors of a matrix are linearly independent since the matrix has a non-zero determinant. Vectors of a matrix are linearly dependent since the matrix has a zero determinant. This means we cannot solve the matrix (the equation system) and it has no inverse.

In [5]:
#calculating the determinant for a 3x3 matrix with a zero determinant (we can't solve the equation system/ the matrix & it has no inverse)
my3Matrix=np.array([[3,4,5],[1,2,3],[5,6,7]])
np.linalg.det(my3Matrix)

0.0

Two very nice applications of the value of a determinant are associated with area and volume. By evaluating a determinant, you can find the area of a triangle, the vertices of which are described in the coordinate plane. And, even better, the value of a determinant is linked to the volume of a parallelepiped.

The area of a triangle is found by taking one half the absolute value of the determinant of the matrix formed using the coordinates of the triangle and a column of 1s.

In [6]:
# here we have atriangle with coordinates/ vertices (2,4) & (9,6) & (7,-3)
coordinatesMatrix=np.array([[2,4,1],[9,6,1],[7,-3,1]])
triangleArea=abs(1/2* np.linalg.det(coordinatesMatrix))
print(triangleArea)

29.500000000000007


calculating parallelogram area ==> One of two different situations may occur with the parallelograms graphed in two-space: 

(1) One of the vertices of the parallelogram is at the origin, or 

(2) none of the vertices is at the origin. Having a vertex at the origin makes the work easier, but it’s not really all that hard to deal with a parallelogram that’s out there.

To find the area of a parallelogram that has one of its vertices at the origin (0,0), you just need the coordinates of the vertices that are directly connected with the origin by one of the sides of the parallelogram. The area of a parallelogram with one vertex at the origin and with coordinates of points (x1,y1) and (x2,y2) connecting a side of the parallelogram with the origin has an area equal to the absolute value of the determinant.

When a parallelogram doesn’t have a vertex at the origin, you adjust or slide the parallelogram — maintaining its size and shape — until one of the verti ces ends up at the origin.

In [7]:
# finding a parallelogram area that has one of its vertices at the origin and the coordinates of the vertices 
# that are directly connected with the origin by one of the sides of the parallelogram are (1,2) & (6,5)
coordinatesAsIs=np.array([[1,2],[6,5]])
coordinatesTransposed=coordinatesAsIs.transpose()
print(coordinatesTransposed)
print('###################')
areaOfParallelogram=abs(np.linalg.det(coordinatesTransposed))
print(areaOfParallelogram)

[[1 6]
 [2 5]]
###################
7.000000000000001


In [8]:
# finding a parallelogram area that doesn’t have a vertex at the origin and the coordinates are (3,1)& (7,3) & (9,11) & (5,9).
# we use the equation here: https://www.youtube.com/watch?v=o83H3mG7LRA
# remember that you must list the coordinates anti clockwise عكس عقارب الساعة

coordinatesAsIs=np.array([[3,1],[7,3],[9,11],[5,9]])
coordinatesAsList=coordinatesAsIs.tolist()
print(coordinatesAsList)
sumOfDeterminants=0
smallArrayOfCalculation=0
for i in range(len(coordinatesAsList)):
    print(i)
    print(coordinatesAsList[i])
    
    if i< len(coordinatesAsList)-1:
        print(np.array([coordinatesAsList[i],coordinatesAsList[i+1]]))        
        smallArrayDeterminant=np.linalg.det(np.array([coordinatesAsList[i],coordinatesAsList[i+1]]))        
    
    else:
        print(np.array([coordinatesAsList[i],coordinatesAsList[0]]))
        smallArrayDeterminant=np.linalg.det(np.array([coordinatesAsList[i],coordinatesAsList[0]]))
        
    sumOfDeterminants=sumOfDeterminants+smallArrayDeterminant
print(sumOfDeterminants)
print('###################')
areaOfShape=1/2*sumOfDeterminants
print(areaOfShape)

[[3, 1], [7, 3], [9, 11], [5, 9]]
0
[3, 1]
[[3 1]
 [7 3]]
1
[7, 3]
[[ 7  3]
 [ 9 11]]
2
[9, 11]
[[ 9 11]
 [ 5  9]]
3
[5, 9]
[[5 9]
 [3 1]]
56.0
###################
28.0


Parallelpiped volume can be calculated When a parallelepiped has one of its vertices at the origin, then the volume of that parallelepiped is found with the determinant of a 3x3 matrix using the coordinates of the vertices at the other end of the sides of the parallelepiped that all meet at the origin.

In [9]:
# finding a parallelpiped volume that has one of its vertices at the origin and the coordinates of the vertices 
# that are directly connected with the origin  of the parallelpiped are (2,2,5) & (-1,2,1)& (1,6,2)

coordinatesAsIs=np.array([[2,2,5],[-1,2,1],[1,6,2]])
coordinatesTransposed=coordinatesAsIs.transpose()
print(coordinatesTransposed)
print('###################')
areaOfParallelogram=abs(np.linalg.det(coordinatesTransposed))
print(areaOfParallelogram)

[[ 2 -1  1]
 [ 2  2  6]
 [ 5  1  2]]
###################
37.99999999999999
