
<h1 align=center> Linear Algebra: Chapter 8 (Properties of Determinants)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

The determinant of matrix A is equal to the determinant of the transpose of matrix A: det (A) = det (AT).

In [1]:
import numpy as np
my3Matrix=np.array([[1,2,3],[4,5,0],[3,1,2]])
print(np.linalg.det(my3Matrix))
print('#############')

my3MatrixTransposed=my3Matrix.transpose()
print(np.linalg.det(my3MatrixTransposed))

-38.99999999999999
#############
-38.99999999999999


The determinant of matrix A is equal to the reciprocal (multiplicative inverse of the determinant of the inverse of matrix A: 

det(A)=1/det(A**-1)

In [2]:
print(1/np.linalg.det(np.linalg.inv(my3Matrix)))

-38.99999999999999


The inverse of a matrix exists only if the determinant is not equal to 0.

The determinant of the matrix B when multiplied by the inverse matrix B-1 equals 1

The determinant of the matrix resulting from multiplying the matrix B by the inverse matrix B-1 equals 1. Note that B multiplied by B-1 is the identity matrix. So the determinant of the identity matrix is 1

In [3]:
B=np.array([[1,3,3],[1,6,3],[1,3,4]])
B_Inverse=np.linalg.inv(B)
print(np.linalg.det(B))
print('####################')
print(np.linalg.det(B_Inverse))
print('######################')
print(np.linalg.det(B)*np.linalg.det(B_Inverse))# the multiplication of the matrix and the inverse is 1

print('######################')
print(np.matmul(B,B_Inverse)) # the result is the identity matrix
print('######################')
print(np.linalg.det(np.matmul(B,B_Inverse))) # the determinant of the identity matrix is 1

3.0000000000000004
####################
0.33333333333333315
######################
0.9999999999999996
######################
[[ 1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -5.55111512e-17  1.00000000e+00]]
######################
0.9999999999999999


Interchanging two rows (or columns) of a matrix results in a determinant of the opposite sign

In [4]:
a3=np.array([[1,3,5],[1,6,0],[-2,3,4]])
print(a3)
print(np.linalg.det(a3))
print('#####################')
a3Interchange=np.array([[1,3,5],[-2,3,4],[1,6,0]])
print(a3Interchange)
print(np.linalg.det(a3Interchange))# the determinant is with an opposite sign after the interchange

[[ 1  3  5]
 [ 1  6  0]
 [-2  3  4]]
87.0
#####################
[[ 1  3  5]
 [-2  3  4]
 [ 1  6  0]]
-87.0


In [5]:
#this is to know how to interchange rows

a3=np.array([[1,3,5],[1,6,0],[-2,3,4]])
print(a3)
print('################')

#the interchange process to be done here row by row . It is replacement not interchange
print('row 0 before interchange: '+str(a3[0,:])) # print all the columns in row 0
print('################')
a3[0,:]=a3[1,:]
print('row 0 after interchange: '+str(a3[0,:]))# print all the columns in row 0
print('################')
print('row 0 before interchange: '+str(a3[1,:])) # print all the columns in row 1
print('################')

a3[1,:]=a3[1,:]
print('row 0 after interchange: '+str(a3[1,:])) # print all the columns in row 1
print('################')
print('The whole matrix after interchange: '+str(a3))# the final matrix after interchange

[[ 1  3  5]
 [ 1  6  0]
 [-2  3  4]]
################
row 0 before interchange: [1 3 5]
################
row 0 after interchange: [1 6 0]
################
row 0 before interchange: [1 6 0]
################
row 0 after interchange: [1 6 0]
################
The whole matrix after interchange: [[ 1  6  0]
 [ 1  6  0]
 [-2  3  4]]


In [6]:
# here we do the interchange in one step
a3=np.array([[1,3,5],[1,6,0],[-2,3,4]])
print(a3)
print('################')
a3[0,:],a3[1,:],a3[2,:]=a3[1,:],a3[0,:],a3[2,:]
print('the whole matric after interchange'+str(a3))

[[ 1  3  5]
 [ 1  6  0]
 [-2  3  4]]
################
the whole matric after interchange[[ 1  6  0]
 [ 1  6  0]
 [-2  3  4]]


In [7]:
# interchange two rows and interchange two columns of the same matrix?” Your instinct may be to say that the two actions 
# cancel one another out. Your instincts are right

In [8]:
a3=np.array([[1,-2,6],[1,0,2],[-5,3,1]])
print(a3)
print(np.linalg.det(a3))
print('#####################')
a3Interchange1=np.array([[-5,3,1],[1,0,2],[1,-2,6]])
print(a3Interchange1)
print(np.linalg.det(a3Interchange1))
print('#####################')
a3Interchange2=np.array([[3,-5,1],[0,1,2],[-2,1,6]])
print(a3Interchange2)
print(np.linalg.det(a3Interchange2))

[[ 1 -2  6]
 [ 1  0  2]
 [-5  3  1]]
34.00000000000001
#####################
[[-5  3  1]
 [ 1  0  2]
 [ 1 -2  6]]
-34.00000000000001
#####################
[[ 3 -5  1]
 [ 0  1  2]
 [-2  1  6]]
34.00000000000001


If a matrix has a row or column of zeros, then the determinant associated with that matrix is equal to zero.

In [9]:
F=np.array([[0,0,0,0],[3,-2,5,-2],[0,6,1,6],[-3,1,4,1]])
print(F)
print(np.linalg.det(F))

[[ 0  0  0  0]
 [ 3 -2  5 -2]
 [ 0  6  1  6]
 [-3  1  4  1]]
0.0


If the corresponding elements in two rows (or columns) of a matrix are all equal, then the value of that determinant is zero.

In [10]:
F=np.array([[2,5,6,5],[3,-2,5,-2],[0,6,1,6],[-3,1,4,1]])
print(F)
print(np.linalg.det(F))

[[ 2  5  6  5]
 [ 3 -2  5 -2]
 [ 0  6  1  6]
 [-3  1  4  1]]
0.0


If every element of a row (or column) of a matrix is multiplied by a particular scalar k, then the determinant of that matrix is k times the determinant of the original matrix

In [11]:
G=np.array([[2,3,5],[1/2,6,5/6],[-2,3,1]])
print(np.linalg.det(G)*6)
print('#################')
print(6*np.linalg.det(G))

408.0000000000001
#################
408.0000000000001


A common situation in matrices used in practical applications is that you have one or more elements that are decimals. And the decimals often range in the number of places; you even find some matrices using scientific nota tion to represent the numbers.

A number written in scientific notation consists of the product of (a) a number between 0 and 10 and (b) a power of 10.

https://www.dummies.com/education/math/algebra/how-to-write-numbers-in-scientific-notation/

In [12]:
H=np.array([[2*10**-4,5*10**-5,6*10**-6,5*10**-4],[3,-2,0.00005,-2],[0,6,0.0001,6],[-3,1,0.004,1]])
print(np.linalg.det(H))
print(np.linalg.det(H)*1000000)

-3.293999999999998e-05
-32.939999999999976


If matrix A is an upper (or lower) triangular matrix, then the determinant of A is equal to the product of the elements lying on that main diagonal So, The determinant of an identity matrix is equal to 1.

In [13]:
N=np.array([[2,1,4,3],[0,-2,1,-6],[0,0,7,2],[0,0,0,3]])
print(np.linalg.det(N))
print('diagonal product is: '+str(2*-2*7*3)) # same as the determinant

-83.99999999999999
diagonal product is: -84


The determinant of an identity matrix is equal to 1.

In [14]:
identityMatrix=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(np.linalg.det(identityMatrix))
                    


1.0


If a square matrix has 0s above or below the reverse diagonal (opposite of the main diagonal), then the value of the determinant of the matrix is either the product of the elements along that reverse diagonal or -1 times the product of the elements on that diagonal.

In [15]:
triangularReverse=np.array([[0,0,5],[0,3,0],[4,0,0]])
print(np.linalg.det(triangularReverse))

-59.999999999999986


If A and B are two nxn matrices, then det(AB) = [det(A)][det(B)].. Note that we will use square matrices here

In [16]:
A=np.array([[1,2,3],[4,5,0],[3,1,2]])
B=np.array([[2,0,-1],[4,5,3],[1,1,7]])
print(np.linalg.det(np.matmul(A,B)))
print(np.linalg.det(A)*np.linalg.det(B))

-2534.999999999999
-2535.0000000000014
