
<h1 align=center> Linear Algebra: Chapter 9 (subspaces Of a Vector Space)</h1>



This course is developed by Dr. Mohamed Gabr (gbrbreen2@gmail.com) as an introduction to mathematics for AI. The course focuses on using Python for Linear Algebra calculations.

In [2]:
#null space using sympy
from sympy import Matrix
A = Matrix([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])
print(A.nullspace())

[Matrix([
[-15],
[  6],
[  1],
[  0],
[  0]]), Matrix([
[0],
[0],
[0],
[1],
[0]]), Matrix([
[   1],
[-1/2],
[   0],
[   0],
[   1]])]


In [6]:
# to be sure we multiply the nullspace by the second vector in the resulting matrix (nullspace matrix)
A*A.nullspace()[1] 

Matrix([
[0],
[0]])

In [8]:
# null space using numpy
import numpy as np
A_leftSide = np.array([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])
x_rightSide=np.array([0,0])

print(np.linalg.lstsq(A_leftSide,x_rightSide, rcond=None))

(array([0., 0., 0., 0., 0.]), array([], dtype=float64), 2, array([11.05973286,  2.94657583]))


In [9]:
# check the resulting solution (0,0,0,0,0)
unknownVector=np.linalg.lstsq(A_leftSide,x_rightSide, rcond=None)[0]
print(unknownVector)
print(np.asarray(unknownVector))
np.set_printoptions(formatter={'float_kind':'{:f}'.format})# this line is to convert scientific notation to normal numbers before printing
print(np.matmul(A_leftSide,np.asarray(unknownVector)))

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0.000000 0.000000]


Nullspace and the relation with linear independence:

if the column vectors of the square matrix (columns after making them vectors) are linearly independent, the nullspace of the matrix is only going to be the zero vector. In other words, if the nullspace of the matrix is the zero vector, the column vectors (the columns) of the matrix are linearly independent.

In [10]:
B=Matrix([[2,5,3],[1,1,1],[4,-2,0]]) # from sympy
#myLinearlyIndependentColumns= Matrix([[2,1,4],[5,1,-2],[3,1,0]])
B.nullspace() # the result is the zero vector. In the next cell, let us check if the column vectors are linearly independent

[]

In [11]:
import numpy as np
B=np.array([[2,5,3],[1,1,1],[4,-2,0]])
print(B)
print(np.linalg.det(B)) # the determinant is not zero. So, the matrix is linearly independent

# here, we transpose the matrix
V =  np.transpose(B)#transpose
print(V)
np.linalg.det(V) # the determinant is not zero. So, the transpose of the matrix is linearly independent

[[ 2  5  3]
 [ 1  1  1]
 [ 4 -2  0]]
5.999999999999998
[[ 2  1  4]
 [ 5  1 -2]
 [ 3  1  0]]


5.999999999999996

The column space of a matrix is the set of all linear combinations of the columns of the matrix. For example, consider the matrix A, which has dimension 3x4. The column space for matrix A consists of four 3x1 vectors. And the four vectors constitute a spanning set.

In [12]:
A = Matrix([[1,-1,2,0],[3,2,0,1],[-1,0,1,-2]])# from sympy
A.columnspace()

[Matrix([
 [ 1],
 [ 3],
 [-1]]), Matrix([
 [-1],
 [ 2],
 [ 0]]), Matrix([
 [2],
 [0],
 [1]])]

If a vector b is in the Column space of A, then b is the result of a linear combination of the column vectors in A. For example, I look at matrix A, and want to determine if vector b, shown here, is in the Column space A. We can know this by solving the equation and s the matrix is not a square matrix we can ONLY use lstsq (NOT solve).

In [13]:
A_leftSide=np.array([[1,-1,2,0],[3,2,0,1],[-1,0,1,-2]])
b_rightSide=np.array([13,1,0])

print(np.linalg.lstsq(A_leftSide,b_rightSide, rcond=None))

(array([2.000000, -3.000000, 4.000000, 1.000000]), array([], dtype=float64), 3, array([4.052706, 2.564288, 1.732051]))


In [14]:
# check the resulting solution (2,3,4,1)
unknownVector=np.linalg.lstsq(A_leftSide,b_rightSide, rcond=None)[0]
print(unknownVector)
print(np.asarray(unknownVector))
np.set_printoptions(formatter={'float_kind':'{:f}'.format})# this line is to convert scientific notation to normal numbers before printing
print(np.matmul(A_leftSide,np.asarray(unknownVector)))

[2.000000 -3.000000 4.000000 1.000000]
[2.000000 -3.000000 4.000000 1.000000]
[13.000000 1.000000 0.000000]
